$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$assetsDir = Join-Path $root "assets/img"
$dataFile = Join-Path $root "_data/image_dimensions.yml"
$separator = [IO.Path]::DirectorySeparatorChar

$magickCandidates = @(
  (Join-Path $root ".tools/imagemagick-portable/magick.exe"),
  "magick.exe"
)

$magick = $magickCandidates |
  Where-Object {
    if ([IO.Path]::IsPathRooted($_)) {
      Test-Path $_
    }
    else {
      $null -ne (Get-Command $_ -ErrorAction SilentlyContinue)
    }
  } |
  Select-Object -First 1

if (-not $magick) {
  throw "No se encontro ImageMagick. Consulta README.md para preparar la herramienta."
}

$references = [System.Collections.Generic.HashSet[string]]::new(
  [StringComparer]::OrdinalIgnoreCase
)

Get-ChildItem $root -Recurse -File |
  Where-Object {
    -not $_.FullName.StartsWith((Join-Path $root "_site") + $separator) -and
    -not $_.FullName.StartsWith((Join-Path $root ".git") + $separator) -and
    -not $_.FullName.StartsWith((Join-Path $root ".tools") + $separator) -and
    -not $_.FullName.StartsWith((Join-Path $root "docs") + $separator) -and
    -not $_.FullName.StartsWith((Join-Path $root "scripts") + $separator) -and
    $_.Extension -in ".md", ".html", ".yml"
  } |
  ForEach-Object {
    $content = Get-Content -Raw -Encoding UTF8 $_.FullName

    foreach ($match in [regex]::Matches($content, "/?assets/img/[^`"'\s]+")) {
      $url = "/" + $match.Value.TrimStart([char]"/")
      $extension = [IO.Path]::GetExtension($url)

      if ($extension -in ".jpg", ".jpeg", ".png") {
        $references.Add($url) | Out-Null
      }
    }
  }

$metadata = [System.Collections.Generic.List[object]]::new()
$sourceBytes = 0L
$webpBytes = 0L

foreach ($url in $references | Sort-Object) {
  $relativePath = $url.TrimStart([char]"/").Replace([char]"/", $separator)
  $source = Join-Path $root $relativePath

  if (-not (Test-Path $source)) {
    Write-Warning "No existe el asset referenciado: $url"
    continue
  }

  $output = [IO.Path]::ChangeExtension($source, ".webp")
  & $magick $source -auto-orient -resize "1600x1600>" -strip -quality 78 $output

  if ($LASTEXITCODE -ne 0) {
    throw "No se pudo optimizar '$url'"
  }

  $dimensions = (& $magick identify -format "%w %h" $source).Split(" ")
  if ($LASTEXITCODE -ne 0 -or $dimensions.Count -ne 2) {
    throw "No se pudieron leer las dimensiones de '$url'"
  }

  $sourceBytes += (Get-Item $source).Length
  $webpBytes += (Get-Item $output).Length
  $metadata.Add(
    [pscustomobject]@{
      Url = $url
      Width = $dimensions[0]
      Height = $dimensions[1]
    }
  )
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Generated by scripts/optimize-images.ps1")

foreach ($item in $metadata | Sort-Object Url) {
  $lines.Add("'$($item.Url)':")
  $lines.Add("  width: $($item.Width)")
  $lines.Add("  height: $($item.Height)")
}

[IO.File]::WriteAllLines(
  $dataFile,
  $lines,
  (New-Object Text.UTF8Encoding($false))
)

$savedBytes = $sourceBytes - $webpBytes
$savedPercent = if ($sourceBytes -gt 0) {
  [math]::Round(($savedBytes / $sourceBytes) * 100, 1)
}
else {
  0
}

Write-Host "Imagenes optimizadas: $($metadata.Count)"
Write-Host "Originales referenciados: $([math]::Round($sourceBytes / 1MB, 2)) MB"
Write-Host "Derivados WebP: $([math]::Round($webpBytes / 1MB, 2)) MB"
Write-Host "Reduccion estimada para navegadores modernos: $savedPercent%"
